# Generated by Django 6.0.1 on 2026-01-09 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoadSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_longitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                (
                    "start_latitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                ("end_longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("end_latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("length", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpeedReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average_speed", models.DecimalField(decimal_places=2, max_digits=5)),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "road_segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speedreadings",
                        to="monitoring.roadsegment",
                    ),
                ),
            ],
        ),
    ]
